version: "3.9"
services:
  scipy-notebook:
    build: .
    image: jupyter_playground
    volumes:
      - ${LOCAL_WORKING_DIR}:/home/jovyan/work
    ports:
      - ${PORT}:8888
    container_name:   jupyter_notebook

